create table topicos(

    id bigint generated by default as identity not null,
    mensaje varchar(500) not null,
    nombrecurso varchar(30) not null,
    titulo varchar(50) not null,
    fechacreacion date not null default current_date,
    activo boolean default true,

    primary key(id)

);